### ISSUE TITLE
Use pug or similar tools to generate the document index page

### ISSUE THREAD

**Issue by Ailrun** [CUTE-Lang/miniCUTE#92]
**Is your feature request related to a problem? Please describe.**
Current document does not include any package-specific links. However, it's hard to add them because they have dynamic paths using their versions.

**Describe the solution you'd like**
Use pug or other templating tools.

**Comment by Ailrun** [comment]
Or just use jekyll to generate index.html

**Comment by ENvironmentSet** [comment]
I've found some document builder that is customizable through react.

- [Docz](https://www.docz.site): Could be used with Gatsby(Actually, I found this on Gatsby's official document). supports MDX.
- [Docusaurus](https://docusaurus.io): Open source documentation tool by Facebook.

since we now react well, we could be happy with these tools

**Comment by Ailrun** [comment]
@ENvironmentSet Look not bad. However, they are not tools to generate static site, and they are more like __document__ builders, right? What I am looking for in this issue is something to generate (only) index page for the documentation, not documentation itself. So I'm sorry to say this, but I think those tools are not appropriate for that purpose.

**Comment by ENvironmentSet** [comment]
Ooops, I missed important point :(

anyway, let's try pug first. I love it.

**Comment by Ailrun** [comment]
Resolved by 5524ba200b1f1ecc770c473d72eac329c0072773
